const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
  id: { type: Number},
  imgUrl: { type: String},
  name: { type: String},
  description: { type: String},
  price: { type: Number},
  amount: { type: Number, default : 1}
});

module.exports = mongoose.model("Product", productSchema);

const Product = mongoose.model('Product', productSchema);

const products = [ 
  { id: 0,
    imgUrl: "/images/truffle.png",
    name: "Truffle Cream Soup",
    description: "A soup with assorted truffles cooked with vegetable stock, milk, and cream.",
    price: 20 },
  { id: 1,
    imgUrl: "/images/chateaubriand.jpg",
    name: "Chateaubriand",
    description: "Thai french beef tenderloin, mash potato, Ma-Kueaun and Red wine sauce.",
    price: 21 },
  { id: 2,
    imgUrl: "/images/foiegras.jpg",
    name: "Foie Gras",
    description: "Pan-Seared Foie Gras, corn Puree, salted crumble, apple longan balsamic reduction.",
    price: 25 },
  { id: 3,
    imgUrl: "/images/dishes01.jpg",
    name: "Confit De Cannard",
    description: " ",
    price: 18 },
  { id: 4,
    imgUrl: "/images/dishes02.jpg",
    name: "Escargots De Bourgogne",
    description: " ",
    price: 18 },
  { id: 5,
    imgUrl: "/images/dishes03.jpg",
    name: "Bouillabaisse",
    description: " ",
    price: 19 },
  { id: 6,
    imgUrl: "/images/dishes04.jpg",
    name: "Duck leg Confit",
    description: " ",
    price: 20 },
  { id: 7,
    imgUrl: "/images/sweets01.jpg",
    name: "Crème Brulee",
    description: " ",
    price: 10 },
  { id: 8,
    imgUrl: "/images/sweets04.jpg",
    name: "Clafoutis",
    description: " ",
    price: 10 },
  { id: 9,
    imgUrl: "/images/sweets03.jpg",
    name: "Madeleines",
    description: " ",
    price: 9 },
  { id: 10,
    imgUrl: "/images/sweets02.jpg",
    name: "Macaron",
    description: " ",
    price: 5 },
  { id: 11,
    imgUrl: "/images/soup01.jpg",
    name: "Consomme",
    description: " ",
    price: 12 },
  { id: 12,
    imgUrl: "/images/soup02.jpg",
    name: "Soup A Loignon",
    description: " ",
    price: 15 },
  { id: 13,
    imgUrl: "/images/soup03.jpg",
    name: "Butternut Soup",
    description: " ",
    price: 17 },
  { id: 14,
    imgUrl: "/images/soup04.jpg",
    name: "Crab Bisque",
    description: " ",
    price: 15 }
];

products.forEach(async (product) => {
  await Product.updateOne({ id: product.id }, { $set: product }, { upsert: true });
});